// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.clerk.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.clerk.domain.DataRow;
import org.clerk.domain.DataRowDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect DataRowDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataRowDataOnDemand: @Component;
    
    private Random DataRowDataOnDemand.rnd = new SecureRandom();
    
    private List<DataRow> DataRowDataOnDemand.data;
    
    public DataRow DataRowDataOnDemand.getNewTransientDataRow(int index) {
        DataRow obj = new DataRow();
        return obj;
    }
    
    public DataRow DataRowDataOnDemand.getSpecificDataRow(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DataRow obj = data.get(index);
        Long id = obj.getId();
        return DataRow.findDataRow(id);
    }
    
    public DataRow DataRowDataOnDemand.getRandomDataRow() {
        init();
        DataRow obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DataRow.findDataRow(id);
    }
    
    public boolean DataRowDataOnDemand.modifyDataRow(DataRow obj) {
        return false;
    }
    
    public void DataRowDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DataRow.findDataRowEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DataRow' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DataRow>();
        for (int i = 0; i < 10; i++) {
            DataRow obj = getNewTransientDataRow(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
