// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.clerk.domain;

import java.util.List;
import org.clerk.domain.DataRow;
import org.clerk.domain.DataRowDataOnDemand;
import org.clerk.domain.DataRowIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DataRowIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataRowIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataRowIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DataRowIntegrationTest: @Transactional;
    
    @Autowired
    private DataRowDataOnDemand DataRowIntegrationTest.dod;
    
    @Test
    public void DataRowIntegrationTest.testCountDataRows() {
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", dod.getRandomDataRow());
        long count = DataRow.countDataRows();
        Assert.assertTrue("Counter for 'DataRow' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataRowIntegrationTest.testFindDataRow() {
        DataRow obj = dod.getRandomDataRow();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to provide an identifier", id);
        obj = DataRow.findDataRow(id);
        Assert.assertNotNull("Find method for 'DataRow' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DataRow' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DataRowIntegrationTest.testFindAllDataRows() {
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", dod.getRandomDataRow());
        long count = DataRow.countDataRows();
        Assert.assertTrue("Too expensive to perform a find all test for 'DataRow', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DataRow> result = DataRow.findAllDataRows();
        Assert.assertNotNull("Find all method for 'DataRow' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DataRow' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataRowIntegrationTest.testFindDataRowEntries() {
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", dod.getRandomDataRow());
        long count = DataRow.countDataRows();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DataRow> result = DataRow.findDataRowEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DataRow' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DataRow' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataRowIntegrationTest.testFlush() {
        DataRow obj = dod.getRandomDataRow();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to provide an identifier", id);
        obj = DataRow.findDataRow(id);
        Assert.assertNotNull("Find method for 'DataRow' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDataRow(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DataRow' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataRowIntegrationTest.testMergeUpdate() {
        DataRow obj = dod.getRandomDataRow();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to provide an identifier", id);
        obj = DataRow.findDataRow(id);
        boolean modified =  dod.modifyDataRow(obj);
        Integer currentVersion = obj.getVersion();
        DataRow merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DataRow' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataRowIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", dod.getRandomDataRow());
        DataRow obj = dod.getNewTransientDataRow(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DataRow' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DataRow' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DataRow' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DataRowIntegrationTest.testRemove() {
        DataRow obj = dod.getRandomDataRow();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataRow' failed to provide an identifier", id);
        obj = DataRow.findDataRow(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DataRow' with identifier '" + id + "'", DataRow.findDataRow(id));
    }
    
}
